/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approvePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordAttendance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/next-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createNextPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityPlanView */
        ActivityPlanView: {
            /** Age Max */
            age_max: number;
            /** Age Min */
            age_min: number;
            /** Beginner Friendly */
            beginner_friendly: boolean;
            /**
             * Commitment
             * @enum {string}
             */
            commitment: "taster" | "one_off" | "short_course" | "term";
            /** Cost Sgd */
            cost_sgd: number | string;
            /** Duration Hours */
            duration_hours: number;
            /**
             * Freshness State
             * @enum {string}
             */
            freshness_state: "fresh" | "stale";
            /** Guest Allowed */
            guest_allowed: boolean;
            /** Join Alone Ok */
            join_alone_ok: boolean;
            /** Listing Id */
            listing_id: string;
            /**
             * Nearest Mrt
             * @default null
             */
            nearest_mrt: string | null;
            /** Organiser */
            organiser: string;
            /** Planning Area */
            planning_area: string;
            /** Provider Type */
            provider_type: string;
            /**
             * Schedule Kind
             * @enum {string}
             */
            schedule_kind: "weekly" | "fixed_dates" | "drop_in";
            /**
             * Schedule Note
             * @default null
             */
            schedule_note: string | null;
            /**
             * Session At
             * Format: date-time
             */
            session_at: string;
            /** Session Flexible */
            session_flexible: boolean;
            /** Source Url */
            source_url: string;
            /** Title */
            title: string;
            /** Venue Name */
            venue_name: string;
            /**
             * Verification
             * @enum {string}
             */
            verification: "verified" | "unverified";
            /**
             * Verified At
             * @default null
             */
            verified_at: string | null;
        };
        /** AdaptationView */
        AdaptationView: {
            /**
             * Action
             * @enum {string}
             */
            action: "none" | "replan" | "try_to_commit" | "hold_this_week";
            /** Dislikes Recorded */
            dislikes_recorded: number;
            /** Persisted */
            persisted: boolean;
            /** Preference Changes */
            preference_changes?: components["schemas"]["PreferenceChange"][];
            /** Reason Codes */
            reason_codes?: string[];
        };
        /** AdultSummaryView */
        AdultSummaryView: {
            /** Organiser */
            organiser: string;
            /** Source Url */
            source_url: string;
            /**
             * Timing
             * Format: date-time
             */
            timing: string;
            /**
             * Timing Note
             * @default null
             */
            timing_note: string | null;
            /** Venue */
            venue: string;
        };
        /** ApiErrorView */
        ApiErrorView: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Ok
             * @default false
             * @constant
             */
            ok: false;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /** ApprovalRequirements */
        ApprovalRequirements: {
            /**
             * Attendance Required
             * @default true
             */
            attendance_required: boolean;
            /** Provider Listing Ids */
            provider_listing_ids?: string[];
            /**
             * Spend Ceiling Sgd
             * @default null
             */
            spend_ceiling_sgd: number | string | null;
            /** Spend Required */
            spend_required: boolean;
        };
        /** AttendanceStepResponse */
        AttendanceStepResponse: {
            adaptation: components["schemas"]["AdaptationView"];
            /** Ok */
            ok: boolean;
        };
        /** BookingStepResponse */
        BookingStepResponse: {
            /** Bookings */
            bookings?: components["schemas"]["BookingView"][];
            /** Ok */
            ok: boolean;
            /** Outcome */
            outcome: string;
            /** @default null */
            plan: components["schemas"]["PlanView"] | null;
        };
        /** BookingView */
        BookingView: {
            activity: components["schemas"]["ActivityPlanView"];
            adult_summary: components["schemas"]["AdultSummaryView"];
            /** Booking Id */
            booking_id: string;
            preparation: components["schemas"]["PreparationView"];
            /**
             * Sandbox
             * @default true
             */
            sandbox: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "booked" | "failed";
        };
        /** DemoApproveRequest */
        DemoApproveRequest: {
            /** Plan Id */
            plan_id: string;
            /** Provider Listing Ids */
            provider_listing_ids?: string[];
            /**
             * Spend Ceiling Sgd
             * @default null
             */
            spend_ceiling_sgd: number | string | null;
            /** Teen Id */
            teen_id: string;
        };
        /** DemoAttendanceRequest */
        DemoAttendanceRequest: {
            /** Attended */
            attended: boolean;
            /** Booking Id */
            booking_id: string;
            /**
             * Debrief
             * @default null
             */
            debrief: string | null;
            /** Teen Id */
            teen_id: string;
        };
        /** DemoNextPlanRequest */
        DemoNextPlanRequest: {
            /** Teen Id */
            teen_id: string;
        };
        /** DemoSetupRequest */
        DemoSetupRequest: {
            /** Cold Start Vibes */
            cold_start_vibes?: ("sporty" | "artistic" | "chill" | "explorative")[];
            /** Declared Age */
            declared_age: number;
            /** Goal */
            goal: string;
            /** Hours Per Week */
            hours_per_week: number;
            /**
             * Max Travel Min
             * @default 45
             */
            max_travel_min: number;
            /** Money Total Sgd */
            money_total_sgd: number | string;
            /** Parental Rules */
            parental_rules?: ("verified_only" | "no_private_unverified" | "no_paid_activities")[];
            /** Tries Total */
            tries_total: number;
        };
        /** HealthView */
        HealthView: {
            /** Ok */
            ok: boolean;
            /** Ready For Real Planning */
            ready_for_real_planning: boolean;
            /** Real Activities */
            real_activities: number;
            /** Verified Activities */
            verified_activities: number;
        };
        /** PlanOptionView */
        PlanOptionView: {
            approval_requirements: components["schemas"]["ApprovalRequirements"];
            /** Outcome */
            outcome: string;
            plan: components["schemas"]["PlanView"];
        };
        /** PlanStepResponse */
        PlanStepResponse: {
            /** @default null */
            approval_requirements: components["schemas"]["ApprovalRequirements"] | null;
            /** Ok */
            ok: boolean;
            /** Outcome */
            outcome: string;
            /** @default null */
            plan: components["schemas"]["PlanView"] | null;
            /** Teen Id */
            teen_id: string;
        };
        /** PlanView */
        PlanView: {
            /** Activities */
            activities: components["schemas"]["ActivityPlanView"][];
            /**
             * Binding Constraint
             * @default null
             */
            binding_constraint: string | null;
            /** Plan Id */
            plan_id: string;
            /** Thin */
            thin: boolean;
            /** Total Cost Sgd */
            total_cost_sgd: number | string;
        };
        /** PreferenceChange */
        PreferenceChange: {
            /** After Confidence */
            after_confidence: number;
            /** After Value */
            after_value: number;
            /**
             * Axis
             * @enum {string}
             */
            axis: "indoor_outdoor" | "team_solo" | "contact_noncontact" | "intensity" | "competitive_social";
            /** Before Confidence */
            before_confidence: number;
            /** Before Value */
            before_value: number;
            /**
             * Evidence
             * @enum {string}
             */
            evidence: "seed" | "debrief" | "attendance";
        };
        /** PreparationView */
        PreparationView: {
            /** Bring */
            bring: string;
            /** Guest Allowed */
            guest_allowed: boolean;
            /** Meet */
            meet: string;
            /** People Come Alone */
            people_come_alone: boolean;
        };
        /** ShortlistStepResponse */
        ShortlistStepResponse: {
            /** Ok */
            ok: boolean;
            /** Options */
            options: components["schemas"]["PlanOptionView"][];
            /** Teen Id */
            teen_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    approvePlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoApproveRequest"];
            };
        };
        responses: {
            /** @description Successful demo operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingStepResponse"];
                };
            };
            /** @description Safe frontend error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorView"];
                };
            };
        };
    };
    recordAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoAttendanceRequest"];
            };
        };
        responses: {
            /** @description Successful demo operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceStepResponse"];
                };
            };
            /** @description Safe frontend error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorView"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful demo operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthView"];
                };
            };
            /** @description Safe frontend error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorView"];
                };
            };
        };
    };
    createNextPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoNextPlanRequest"];
            };
        };
        responses: {
            /** @description Successful demo operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanStepResponse"];
                };
            };
            /** @description Safe frontend error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorView"];
                };
            };
        };
    };
    createPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoSetupRequest"];
            };
        };
        responses: {
            /** @description Successful demo operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortlistStepResponse"];
                };
            };
            /** @description Safe frontend error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorView"];
                };
            };
        };
    };
}
